apiVersion: v1
kind: ConfigMap
metadata:
  name: elsaworkflow-adminapi
  namespace: test
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/hit"
data:
  Consul__Keys: <Consul__Keys>
  Consul__Server: <Consul__Server>
  Consul__Token: <Consul__Token>
  ASPNETCORE_HTTP_PORTS: <ASPNETCORE_HTTP_PORTS>
  ASPNETCORE_ENVIRONMENT: <ASPNETCORE_ENVIRONMENT>
  kubernetes: <kubernetes>
