---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-gateway
  namespace: main
spec:
  selector:
    app.kubernetes.io/name: chatbot-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
